sudo: false
language: java
env:
  - ACTIVATOR_VERSION=1.3.5
jdk: oraclejdk8
install:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
services:
  - elasticsearch
script:
  - ./activator-${ACTIVATOR_VERSION}-minimal/activator ";clean; clean-files; reload; update; test"
